export const PRODUCT_FETCH = "PRODUCT_FETCH";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_STOP_FETCH = "PRODUCT_STOP_FETCH";

export const DEPARTMENT_FETCH = "DEPARTMENT_FETCH";
export const DEPARTMENT_SUCCESS = "DEPARTMENT_SUCCESS";
export const DEPARTMENT_ERROR = "DEPARTMENT_ERROR";

export const CATEGORY_FETCH = "CATEGORY_FETCH";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
